apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: coderworkspaces-provider-secret
type: Opaque
data:
   credentials: ZmxBUFJDdU1aWi03NzBBYzJhUFl3ZjZ1cGpadmpzUzBQ
---
apiVersion: coderworkspaces.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: coderworkspaces-provider-config
spec:
  coder_url: http://host.docker.internal:9090
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: coderworkspaces-provider-secret
      key: credentials